name: Deploy to Amazon S3

on:
  release:
    types: [published]
    
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Node.js
      - uses: actions/checkout@v2
        uses: actions/setup-node@v1
        with:
          node-version: '14'

      - name: Install dependencies
        run: |
          cd front
          npm install

      - name: Build
        run: |
          cd front
          npm run build

      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: fe-issue-tracker-s3
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'ap-northeast-2'
          SOURCE_DIR: 'front/dist'
