name: Deploy to Amazon S3

on:
  push:
    branches:
      - dev-fe

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('front/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14'

      - name: Install dependencies
        run: |
          cd front
          npm install

          - name: Build
          run: |
            cd front
            npm run build
            echo "Build completed. Listing contents of the build directory:"
            ls -al ./front/build/

      - name: List build directory contents
        run: |
          ls -al ./front/build/

      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --acl public-read --follow-symlinks --delete ./front/build/ s3://fe-issue-tracker-s3/
        env:
          AWS_S3_BUCKET: fe-issue-tracker-s3
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
